version: '3.5'
services:
  apache:
    build: apache
    ports:
      - '8040:80'
    volumes:
      - openmct-dist:/usr/local/apache2/htdocs/openmct
  openmct:
    build: openmct
    volumes:
      - openmct-dist:/openmct/site
  couchdb:
    build: couchdb
    expose:
      - '5984:5984'
    volumes:
      - couchdb-data:/opt/couchdb/data
  yamcs:
    image: yamcs/example-simulation
    expose:
      - '8090:8090'
volumes:
  couchdb-data:
  openmct-dist: