version: '3.1'
services:
  apache:
    build: apache
    ports:
      - '8000:80'
    volumes:
      - openmct-dist:/var/www/html
  openmct:
    build: openmct
    volumes:
      - openmct-dist:/openmct/openmct-yamcs
  couchdb:
    build: couchdb
    expose:
      - '5984:5984'
    volumes:
      - couchdb-data:/opt/couchdb/data
  yamcs:
    image: yamcs/example-simulation
    expose:
      - '8090:8090'
volumes:
  couchdb-data:
  openmct-dist: